### ISSUE TITLE
`cargo update` to sgx 1.1.5 fails CI

### ISSUE THREAD

**Issue by Kailai-Wang** [integritee-network/sgx-runtime#60]
As topic, steps to reproduce:
- git clone this repo and `cd sgx-runtime`
- `cargo update` => it will update the SGX dep to 1.1.5
- `cargo check -p test-no-std`

It fails with the errors:
```
error[E0658]: use of unstable library feature 'available_parallelism'
  --> /home/kai/.cargo/git/checkouts/incubator-teaclave-sgx-sdk-f208006cdf70a903/605c8ea/sgx_unwind/build.rs:92:13
   |
92 |             thread::available_parallelism()
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #74479 <https://github.com/rust-lang/rust/issues/74479> for more information
   = help: add `#![feature(available_parallelism)]` to the crate attributes to enable
```

root cause seems to be sgx_unwind 1.1.5 compilation.

Is it known? (or upstream issue?)

**Comment by clangenb** [comment]
Such errors usually occur, when the rust-compiler is older than the crate expects. If you update the rust-toolchain, you will probably find that the feature `available_parallelism` has been stabilized and hence does not need that feature flag anymore.

**Comment by Kailai-Wang** [comment]
> Such errors usually occur, when the rust-compiler is older than the crate expects. If you update the rust-toolchain, you will probably find that the feature `available_parallelism` has been stabilized and hence does not need that feature flag anymore.

Thanks, this means however`rust-toolchain.toml` needs to be updated, right?

**Comment by haerdib** [comment]
Yes. I'd recommend using the same as in our worker repo: https://github.com/integritee-network/worker/blob/master/rust-toolchain.toml#L2

It is working with v1.1.5.

**Comment by Kailai-Wang** [comment]
Thanks @clangenb and @haerdib 
I already submitted a PR for the fix: https://github.com/integritee-network/sgx-runtime/pull/62

I tried to remove the `sgx_tstd` and `sgx_patches` patches too as I saw 1.1.5 was used in worker repo.

**Comment by haerdib** [comment]
Thanks a lot for the PR! Removing the patches seems to be the right choice 👍
